### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Genii1** [corbamico/tbcload#1]
failed parse file (1.tbc), error as (strconv.ParseInt: parsing "Mrgm#='BX<<&bS?7J|C+u^sY??IME+'LhTA)#Q)Fv-7hC)#Q)FFngm#a.JTA.?/kB/wJ9>3T": invalid syntax)

[1.zip](https://github.com/corbamico/tbcload/files/3998200/1.zip)

Any ideas?

**Comment by kleinandreas2002** [comment]
@Genii1 
Did you solve the problem? Or found a solution?

**Comment by kmanev073** [comment]
To everyone struggling with the `ParseInt` error, just find all the `20480` numbers in `encoding.go` and `parser.go` and increase it to `2048000`. You can use a bigger number if it is not enough, it seems the buffer size is the problem.

**Comment by corbamico** [comment]
extend buffer as 2048000, fix this issue
tested on 1.zip file.
