### ISSUE TITLE
Update to newer version

### ISSUE THREAD

**Issue by Bird23** [corbamico/tbcload#2]
Is it possible to update to newer version, because sometimes not the whole file is decompiled and ends with i.E :
[lit-0092]failed parse file (lib_standard_post_func.tbc), error as (object type is not supported)

**Comment by Progress1** [comment]
Same problem/errors here (object type is not supported, strconv.ParseInt: parsing ...)
Check your email (i send you example)

**Comment by fetzerms** [comment]
I am getting the same error. I can share a file in private, if you need.

**Comment by rdpdo** [comment]
Yes, got same error too.... Thanks !

**Comment by kmanev073** [comment]
To everyone struggling with the `ParseInt` error, just find all the `20480` numbers in `encoding.go` and `parser.go` and increase it to `2048000`. You can use a bigger number if it is not enough, it seems the buffer size is the problem.

**Comment by corbamico** [comment]
extend buffer as 2048000, fix this issue

**Comment by corbamico** [comment]
extend buffer as 2048000, fix this issue

**Comment by Progress1** [comment]
Why did you not increase buffers also in `parser.go` as mentioned @kmanev073 ? ;-)
I have still errors: `failed parse file (XXX.tcl), error as (short buffer)` and this maybe helps
