### ISSUE TITLE
Failed parse file

### ISSUE THREAD

**Issue by Bird23** [corbamico/tbcload#3]
Hi Corbamico,

With one file I still get an error:
failed parse file ' filename' , error as (short buffer)

Can I change something, or can you check this ?

Regards,
Bird23

**Comment by corbamico** [comment]
do you have this file to test for sharing? @Bird23

**Comment by Bird23** [comment]
Yes I have attached it. 
[lib_msg.zip](https://github.com/corbamico/tbcload/files/13256192/lib_msg.zip)

**Comment by Bird23** [comment]
I have edited my previous comment and added the file

**Comment by corbamico** [comment]
increase buf to 2M, tested on lib_msg.tbc
thanks @Bird23
